DissertationProject/Controllers/FamilyController.cs
using System;
using DissertationProject.Data;

using DissertationProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DissertationProject.Controllers
{
    [Authorize]
    public class FamilyController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<CustomUserModel> _userManager;
        private readonly ApplicationDbContext _db;

        public FamilyController(RoleManager<IdentityRole> roleManager, UserManager<CustomUserModel> userManager, ApplicationDbContext db)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _db = db;
        }

        public async Task<IActionResult> Manage()
        {
            //Need to return a list of all users that are linked to the current family id of the user that is logged in.
            var FMlist = new List<UserRolesViewModel>();
            CustomUserModel user = await _userManager.GetUserAsync(User);

            var users = await _userManager.Users.ToListAsync();

            if (user != null)
            {
                foreach (var item in users)
                {
                    if (item.FamilyId == user.FamilyId)
                    {
                        //Check for any family members that have the same family id and add them to the list.
                        //Find the family members model using the current iteration of user.
                        var family = await _db.FamilyMembers.FirstOrDefaultAsync(i => i.FamilyMember.Email == item.Email);

                        var accountDetails = new UserRolesViewModel()
                        {
                            FamilyMembers = family,
                            Roles = new List<string>(await _userManager.GetRolesAsync(family.FamilyMember)),
                        };
                        FMlist.Add(accountDetails);
                    }
                }
            }
            //Return the list to the view.
            return View(FMlist);
        }

        public async Task<IActionResult> AddRole(string id)
        {
            //Find the user that has been passed in through the method.
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return RedirectToAction("Index");
            }
            //Need to send the users information accross to the view so that a role can be added to their account.
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(ManageUserRolesViewModel model)
        {
            //Assigns the user and the role to variables.
            var user = await _userManager.FindByIdAsync(model.Member.Id);
            var role = model.Role;

            //Need to remove from any existing roles first and then add to the new role.
            //Remove from existing roles.
            var currentRoles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, currentRoles);

            //Add to new role.
            if (result.Succeeded)
            {
                await _userManager.AddToRoleAsync(user, role);

                //Successful
                TempData["Success"] = "Users Role Changed!";
                return RedirectToAction("Manage");
            }
            else
            {
                TempData["Danger"] = "Error Adding Role!";
                return RedirectToAction("Manage");
            }
        }
    }
}

DissertationProject/Views/Family/AddRole.cshtml
@model CustomUserModel
@{
    ViewData["Title"] = "Add Role";

}
<a class="btn btn-secondary mt-3 mb-5 ms-5" asp-controller="Family" asp-action="Manage" id="backbtn">< Back</a>

<div class="container">
    <div class="row">
        <h1 class="subheading-text my-5">Assign @Model.Fname a Role:</h1>

        <form method="post" class="my-3">
            <input type="hidden" name="Member.Id" value="@Model.Id" />
            <div class="form-check">
                <input class="form-check-input" type="radio" name="Role" id="family_member" value="Family_Member">
                <label class="form-check-label" for="family_member">
                    Family Member Account
                </label>
            </div>
            <div class="form-check mt-2">
                <input class="form-check-input" type="radio" name="Role" id="family_kid" value="Family_Kid">
                <label class="form-check-label" for="family_kid">
                    Child Family Account
                </label>
            </div>
            <button type="submit" asp-controller="Family" asp-action="AddRole" class="btn btn-success mt-4" id="submitRole">Submit Role</button>
        </form>
    </div>
</div>

DissertationProject/Views/Family/Manage.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<UserRolesViewModel>
@{
    ViewData["Title"] = "Settings";
}

<a class="btn btn-secondary mt-3 mb-5 ms-5" asp-controller="Home" asp-action="Settings" id="backbtn">< Back</a>

<div class="container mt-5">
    <div class="row">

        @if (TempData["Success"] != null)
        {
            <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
        }
        @if (TempData["Danger"] != null)
        {
            <p class="alert alert-danger" id="successMessage">@TempData["Danger"]</p>
        }
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Income</th>
                    <th scope="col">Job</th>
                    <th scope="col">Role</th>
                    <th scope="col">Manage</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.FamilyMembers.FamilyMember.Fname @item.FamilyMembers.FamilyMember.Sname</th>
                        <td>@item.FamilyMembers.FamilyMember.Income</td>
                        <td>@item.FamilyMembers.FamilyMember.JobName</td>
                        <td>
                            @foreach (var role in item.Roles)
                            {
                                @role <br />
                            }
                        </td>
                        <td>
                            <a class="btn btn-success" asp-controller="Family" asp-action="AddRole" asp-route-id="@item.FamilyMembers.FamilyMember.Id" id="addrolebtn">Add Role</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


<script>
    setTimeout(function () {
            var successMessage = document.getElementById('successMessage');
            if (successMessage != null) {
                successMessage.remove();
            }
    }, 5000);
</script>