DissertationProject/Areas/Admin/Models/FamilyAdminViewModel.cs
using System;
using DissertationProject.Models;

namespace DissertationProject.Areas.Admin.Models
{
    public class FamilyAdminViewModel
    {
        public FamilyModel Family { get; set; }
        public List<FamilyMembersModel> FamilyMembers { get; set; }
    }
}

DissertationProject/Areas/Admin/Controllers/FamilyAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DissertationProject.Areas.Admin.Models;
using DissertationProject.Data;
using DissertationProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DissertationProject.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class FamilyAdminController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<CustomUserModel> _userManager;
        private readonly ApplicationDbContext _db;

        public FamilyAdminController(RoleManager<IdentityRole> roleManager, UserManager<CustomUserModel> userManager, ApplicationDbContext db)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _db = db;
        }

        public IActionResult Manage()
        {
            // Create an empty list to store FamilyAdminViewModel objects
            var FMlist = new List<FamilyAdminViewModel>();
            // Get all families from the database
            var families = _db.Families.ToList();

            foreach (var family in families)
            {
                // Get all family members associated with the current family
                var familyMembers = _db.FamilyMembers.Where(i => i.Family.Id == family.Id).ToList();

                // Create a new FamilyAdminViewModel object
                var familyViewModel = new FamilyAdminViewModel
                {
                    Family = family,
                    FamilyMembers = familyMembers
                };

                // Add the new FamilyAdminViewModel object to the FMlist
                FMlist.Add(familyViewModel);
            }
            return View(FMlist);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFamily(int id)
        {
            var family = await _db.Families.FindAsync(id);
            if (family == null)
            {
                // return an error message if the family is not found
                TempData["Danger"] = "Family not found.";
            }
            else
            {
                // remove the family from the database
                _db.Families.Remove(family);
                await _db.SaveChangesAsync();

                // return a success message
                TempData["Success"] = "Family removed successfully.";
            }

            // redirect back to the Manage page
            return RedirectToAction("Manage");
        }
    }
}

DissertationProject/Areas/Admin/Views/FamilyAdmin/Manage.cshtml
@using DissertationProject.Areas.Admin.Models;
@model IEnumerable<FamilyAdminViewModel>
@{
    ViewData["Title"] = "Admin Family Manage";
}

<div class="container">
    <div class="row mt-5">
        @if (TempData["Success"] != null)
        {
            <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
        }
        @if (TempData["Danger"] != null)
        {
            <p class="alert alert-danger" id="successMessage">@TempData["Danger"]</p>
        }
        <table class="table mt-5">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Family Name</th>
                    <th scope="col">Amount of Users</th>
                    <th scope="col">Users</th>
                    <th scope="col">Manage</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var family in Model)
                {
                    <tr>
                        <th scope="row"></th>
                        <td>@family.Family.Name</td>
                        <td>@family.FamilyMembers.Count</td>
                        <td>
                            <!--Print the individual users names-->
                            @foreach (var user in family.FamilyMembers)
                            {
                                //@user.FamilyMember.Fname @user.FamilyMember.Sname <br />
                            }
                        </td>
                        <td>
                            @if (family.FamilyMembers.Count == 0)
                            {
                                <form method="post" class="my-3" action="@Url.Action("RemoveFamily", "FamilyAdmin", new { id = family.Family.Id })" onsubmit="return confirm('Are you sure you want to remove this family?');">
                                    <button type="submit" class="btn btn-danger w-100" id="removeFamily">Remove</button>
                                </form>
                            }

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


<script>
    setTimeout(function () {
        var successMessage = document.getElementById('successMessage');
        if (successMessage != null) {
            successMessage.remove();
        }
    }, 5000);</script>