DissertationProject/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DissertationProject.Data;
using DissertationProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DissertationProject.Controllers
{
    [Authorize]
    public class BillsController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<CustomUserModel> _userManager;
        private readonly ApplicationDbContext _db;

        public BillsController(RoleManager<IdentityRole> roleManager, UserManager<CustomUserModel> userManager, ApplicationDbContext db)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _db = db;
        }

        public async Task<IActionResult> ViewAll()
        {
            //Needs to return a list of all the bills linked to the current logged in users family id.
            var bills = new List<FamilyBillModel>();
            CustomUserModel user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                var billsList = _db.FamilyBills.Where(i => i.FamilyId == user.FamilyId).ToList();
                bills = billsList;
            }

            return View(bills);
        }


        public IActionResult AddBill()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> AddBill(FamilyBillModel model)
        {
            //Need to create a method that adds a bill to the database.
            //Need to add the familymodel
            //Need to workout the time remaining left to pay based on when it is due and the current date.
            CustomUserModel user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                if (user.FamilyId != null)
                {
                    var familyId = (int)user.FamilyId;
                    var date = DateTime.Now;
                    var day = date.Day;
                    model.FamilyId = familyId;

                    _db.FamilyBills.Add(model);
                    _db.SaveChanges();
                }
                else
                {
                    TempData["Danger"] = "You need to be a part of a family first! - Please do this in the settings.";
                    return RedirectToAction("ViewAll");
                }
            }
            TempData["Success"] = "Bill successfully added!";
            return RedirectToAction("ViewAll");
        }

        [HttpPost]
        public IActionResult DeleteBill(int id)
        {
            //Need to delete a bill from the database.
            var bill = _db.FamilyBills.Where(i => i.Id == id).FirstOrDefault();
            if (bill != null)
            {
                _db.FamilyBills.Remove(bill);
                _db.SaveChanges();
            }
            TempData["Success"] = "Bill Deleted!";
            return RedirectToAction("ViewAll");
        }
    }
}

DissertationProject/Controllers/BudgetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DissertationProject.Data;
using DissertationProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace DissertationProject.Controllers
{
    [Authorize]
    public class BudgetController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<CustomUserModel> _userManager;
        private readonly ApplicationDbContext _db;

        public BudgetController(RoleManager<IdentityRole> roleManager, UserManager<CustomUserModel> userManager, ApplicationDbContext db)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _db = db;
        }

        public async Task<IActionResult> Manage()
        {
            //Need to return a list of the families budget model.
            var BudgetList = new List<BudgetViewModel>();
            CustomUserModel user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                var budgets = _db.FamilyBudgets.Where(i => i.FamilyId == user.FamilyId).ToList();
                var transactions = _db.FamilyTransactions.Where(i => i.FamilyId == user.FamilyId).ToList();
                var bills = _db.FamilyBills.Where(i => i.FamilyId == user.FamilyId).ToList();

                float totalTransactions = transactions.Sum(item => item.Amount);
                float totalBills = bills.Sum(item => item.Amount);

                foreach (var budget in budgets)
                {
                    var BM = new BudgetViewModel()
                    {
                        Budget = budget,
                        Expenses = totalTransactions + totalBills,
                        Profit = budget.Budget - (totalTransactions + totalBills)
                    };
                    BudgetList.Add(BM);
                }
            }
            return View(BudgetList);
        }

        [HttpPost]
        public async Task<IActionResult> Create(FamilyBudgetModel model)
        {
            //Need to post a familyBudgetModel.
            CustomUserModel user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                if (user.FamilyId != null)
                {
                    model.FamilyId = (int)user.FamilyId;

                    //Add and save to the database.
                    await _db.FamilyBudgets.AddAsync(model);
                    await _db.SaveChangesAsync();
                    TempData["Success"] = "Budget Created!";
                    return RedirectToAction("Manage");
                }
                else
                {
                    //If the familyId is null.
                    TempData["Danger"] = "You need to create or join a family account first!";
                    return RedirectToAction("Manage");
                }
            }
            return RedirectToAction("Manage");
        }

        [HttpPost]
        public async Task<IActionResult> Update(FamilyBudgetModel model)
        {
            //Need to post a familyBudgetModel.
            CustomUserModel user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                if (user.FamilyId != null)
                {
                    model.FamilyId = (int)user.FamilyId;

                    //Add and save to the database.
                    _db.FamilyBudgets.Update(model);
                    await _db.SaveChangesAsync();
                    TempData["Success"] = "Budget Updated!";
                    return RedirectToAction("Manage");
                }
                else
                {
                    //If the familyId is null.
                    TempData["Danger"] = "You need to create or join a family account first!";
                    return RedirectToAction("Manage");
                }
            }
            TempData["Danger"] = "Error Updating Budget!";
            return RedirectToAction("Manage");
        }
    }
}

DissertationProject/Controllers/FamilyController.cs
using System;
using DissertationProject.Data;

using DissertationProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DissertationProject.Controllers
{
    [Authorize]
    public class FamilyController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<CustomUserModel> _userManager;
        private readonly ApplicationDbContext _db;

        public FamilyController(RoleManager<IdentityRole> roleManager, UserManager<CustomUserModel> userManager, ApplicationDbContext db)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _db = db;
        }

        public async Task<IActionResult> Manage()
        {
            //Need to return a list of all users that are linked to the current family id of the user that is logged in.
            var FMlist = new List<UserRolesViewModel>();
            CustomUserModel user = await _userManager.GetUserAsync(User);

            var users = await _userManager.Users.ToListAsync();

            if (user != null)
            {
                foreach (var item in users)
                {
                    if (item.FamilyId == user.FamilyId)
                    {
                        //Check for any family members that have the same family id and add them to the list.
                        //Find the family members model using the current iteration of user.
                        var family = await _db.FamilyMembers.FirstOrDefaultAsync(i => i.FamilyMember.Email == item.Email);

                        var accountDetails = new UserRolesViewModel()
                        {
                            FamilyMembers = family,
                            Roles = new List<string>(await _userManager.GetRolesAsync(family.FamilyMember)),
                        };
                        FMlist.Add(accountDetails);
                    }
                }
            }
            //Return the list to the view.
            return View(FMlist);
        }

        public async Task<IActionResult> AddRole(string id)
        {
            //Find the user that has been passed in through the method.
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return RedirectToAction("Index");
            }
            //Need to send the users information accross to the view so that a role can be added to their account.
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(ManageUserRolesViewModel model)
        {
            //Assigns the user and the role to variables.
            var user = await _userManager.FindByIdAsync(model.Member.Id);
            var role = model.Role;

            //Need to remove from any existing roles first and then add to the new role.
            //Remove from existing roles.
            var currentRoles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, currentRoles);

            //Add to new role.
            if (result.Succeeded)
            {
                await _userManager.AddToRoleAsync(user, role);

                //Successful
                TempData["Success"] = "Users Role Changed!";
                return RedirectToAction("Manage");
            }
            else
            {
                TempData["Danger"] = "Error Adding Role!";
                return RedirectToAction("Manage");
            }
        }
    }
}

DissertationProject/Controllers/TransactionController.cs
using DissertationProject.Data;
using DissertationProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DissertationProject.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<CustomUserModel> _userManager;
        private readonly ApplicationDbContext _db;

        public TransactionController(RoleManager<IdentityRole> roleManager, UserManager<CustomUserModel> userManager, ApplicationDbContext db)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _db = db;
        }

        public async Task<IActionResult> ViewAll()
        {
            //Need to return a list of all transactions that are linked to the current family id of the user that is logged in.
            var TMList = new List<TransactionUserViewModel>();
            CustomUserModel user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                var transactions = _db.FamilyTransactions.Where(i => i.FamilyId == user.FamilyId).ToList();
                foreach (var transaction in transactions)
                {
                    var TM = new TransactionUserViewModel()
                    {
                        Transaction = transaction,
                        //Find the member that made the transaction by the transaction userid.
                        Member = await _userManager.FindByIdAsync(transaction.UserId)
                    };
                    TMList.Add(TM);
                }
            }
            return View(TMList);
        }

        public IActionResult AddTransaction()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddTransaction(FamilyTransactionModel transaction)
        {
            CustomUserModel user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                if (user.FamilyId != null)
                {
                    var familyId = (int)user.FamilyId;

                    transaction.FamilyId = familyId;
                    transaction.Date = DateTime.Now;
                    transaction.UserId = user.Id;
                    transaction.CustomUser = user;
                    _db.FamilyTransactions.Add(transaction);
                    _db.SaveChanges();
                }
                else
                {
                    TempData["Danger"] = "You need to be a part of a family first! - Please do this in the settings.";
                    return RedirectToAction("ViewAll");
                }
            }
            return RedirectToAction("ViewAll");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveMonth()
        {
            //Need to remove the past month from the transactions in the database.
            var date = DateTime.Now;
            var month = date.Month;
            var year = date.Year;
            CustomUserModel user = await _userManager.GetUserAsync(User);

            if (user != null)
            {
                var familyId = user.FamilyId;
                var transaction = _db.FamilyTransactions.Where(i => i.FamilyId == familyId && i.Date.Month < month).ToList();
                if (transaction != null)
                {
                    _db.FamilyTransactions.RemoveRange(transaction);
                    _db.SaveChanges();
                }
            }
            TempData["Success"] = "Past Month Deleted!";
            return RedirectToAction("ViewAll");
        }

        [HttpPost]
        public IActionResult DeleteTransaction(int id)
        {
            //Need to delete a transaction from the database.
            var transaction = _db.FamilyTransactions.Where(i => i.Id == id).FirstOrDefault();
            if (transaction != null)
            {
                _db.FamilyTransactions.Remove(transaction);
                _db.SaveChanges();
            }
            TempData["Success"] = "Transaction Deleted!";
            return RedirectToAction("ViewAll");
        }
    }
}

DissertationProject/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<CustomUserModel> UserManager
@model IEnumerable<ChartViewModel>
@{
    ViewData["Title"] = "Home Page";

    CustomUserModel user = await UserManager.GetUserAsync(User);
    var role = await UserManager.GetRolesAsync(user);
}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>


<!--Index page - Links to other pages.-->
<div class="container mt-5">
    <div class="row white-bg py-4 ps-2">
        <h1 class="subheading-text">Good Morning @user.Fname</h1>
        <h4 class="text">Here is your daily report...</h4>
    </div>

    @if (role.Count == 0)
    {
        <!--Warning block that appears if the user does not have a role.-->
        <div class="row bg-red py-4 p-4 mt-5 border border-danger border-5">
            <h3 class="subheading-text mb-3 text-center">You Are Not Assigned To A Family - Go To The Family Settings To Create Or Join A Family!</h3>
            <a asp-controller="Home" asp-action="Settings" class="btn btn-danger w-100">Family Settings</a>
        </div>
    }

    <div class=" d-flex justify-content-center mt-5">
        <div class="row text-center">

            <div class="col mb-3">
                <div class="card mx-5 homecards" style="width: 18rem;">
                    <div class="row">
                        <div class="col-6">
                            <img src="~/images/settings.gif" alt="settings" class="card-img p-3 d-flex justify-content-center">
                        </div>
                        <div class="col-6">
                            <h5 class="card-title mt-4">Configure Family Settings</h5>
                        </div>
                    </div>
                    <div class="card-body">
                        <p class="card-text ">Connect your family accounts and manage your finances collaboratively with our family settings feature. Get started today!</p>
                    </div>
                    <div class="card-footer">
                        <a asp-controller="Home" asp-action="Settings" class="btn btn-col white-text w-100" id="settingsbtn" name="settingsbtn">Family Settings</a>
                    </div>
                </div>
            </div>

            <div class="col mb-3">
                <div class="card mx-5 homecards" style="width: 18rem;">
                    <div class="row">
                        <div class="col-6">
                            <img src="~/images/credit-card.gif" alt="transactions" class="card-img p-3 d-flex justify-content-center">
                        </div>
                        <div class="col-6">
                            <h5 class="card-title mt-4">Transaction Manager</h5>
                        </div>
                    </div>
                    <div class="card-body">
                        <p class="card-text ">Effortlessly track and manage all transactions with our user-friendly transaction manager. Try it now!</p>
                    </div>
                    <div class="card-footer">
                        <a asp-controller="Transaction" asp-action="ViewAll" class="btn btn-col white-text w-100" id="transactionbtn">Transaction Manager</a>
                    </div>
                </div>
            </div>

            <div class="col mb-3">
                <div class="card mx-5 homecards" style="width: 18rem;">
                    <div class="row">
                        <div class="col-6">
                            <img src="~/images/receipt.gif" alt="bills" class="card-img p-3 d-flex justify-content-center">
                        </div>
                        <div class="col-6">
                            <h5 class="card-title mt-4">Bill Manager</h5>
                        </div>
                    </div>
                    <div class="card-body">
                        <p class="card-text ">Never miss a bill again with our handy bills manager. Stay on top of your finances today!</p>
                    </div>
                    <div class="card-footer">
                        <a asp-controller="Bills" asp-action="ViewAll" class="btn btn-col white-text w-100" id="billid">Bill Manager</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
    @{
        bool hasElements = Model.Any();
        if (hasElements)
        {
            <div class="container my-5">
                <div class="row">
                    <div class="col white-bg m-2 p-3">

                        <div>
                            <h4 class="subheading-text">Money Remaining for the Month:</h4>
                            <h3 class="green-text heading-text">£@Math.Round(Model.Sum(m => m.Profit), 2)</h3>
                        </div>
                        <div class="mb-3">
                            <canvas id="moneyRemainingPieChart" width="300"></canvas>
                        </div>
                        <div class="d-flex align-self-end">
                            <a class="text-black subheading-text" asp-area="" asp-controller="Budget" asp-action="Manage">View Your Statement Screen</a>
                        </div>
                    </div>

                    <div class="col white-bg m-2 p-3">
                        <div class="mb-3">
                            <h4 class="subheading-text">Amount Spent on Transactions Over Time:</h4>
                            <h3 class="red-text heading-text">£@Math.Round(Model.Sum(m => m.Expenses), 2)</h3>
                        </div>
                        <div class="mb-3">
                            <canvas id="linegraph" width="300"></canvas>
                        </div>
                        <div>
                            <a class="text-black subheading-text" asp-area="" asp-controller="Transaction" asp-action="ViewAll">View Your Transactions Screen</a>
                        </div>
                    </div>
            
                </div>
            </div>
        
        }
    }
</div>

<!--Code for charts-->
<script>
    //Pie chart for money remaining
    var moneyRemainingPieChart = document.getElementById("moneyRemainingPieChart");
    // Extract expenses and profit data from the ChartViewModel
    var expenses = @Model.Sum(m => m.Expenses);
    var profit = @Model.Sum(m => m.Profit);

    var data = {
        labels: ["Spent", "Remaining"],
        datasets: [{
            data: [expenses, profit],
            backgroundColor: [
                '#ff4d4d',
                '#32cd32'
            ],
            borderColor: [
                '#ff4d4d',
                '#4dbb4d'
            ],
            borderWidth: 1
        }]
    };

    var options = {
        responsive: true,
        maintainAspectRatio: false,
        legend: {
            display: true,
            position: 'bottom'
        }
    };

    var moneyRemainingPieChart = new Chart(moneyRemainingPieChart, {
        type: 'pie',
        data: data,
        options: options
    });
    

    //line graph showing transactions over time

    var transactionsData = @Html.Raw(Json.Serialize(Model.SelectMany(m => m.Transactions).OrderBy(t => t.Date)));

    var transactionDates = transactionsData.map(function (data) { return data.date; });
    var transactionAmounts = transactionsData.map(function (data) { return data.amount; });

    var chartData = {
        labels: transactionDates,
        datasets: [
            {
                label: "Amount Spent",
                backgroundColor: 'rgba(255, 99, 132, 0.2)',
                borderColor: 'rgba(255, 99, 132, 1)',
                borderWidth: 1,
                pointBackgroundColor: 'rgba(255, 99, 132, 1)',
                pointBorderColor: '#fff',
                pointHoverBackgroundColor: '#fff',
                pointHoverBorderColor: 'rgba(255, 99, 132, 1)',
                data: transactionAmounts
            }
        ]
    };

    var chartOptions = {
        scales: {
            xAxes: [{
                type: 'time',
                distribution: 'linear',
                time: {
                    unit: 'month',
                    displayFormats: {
                        month: 'MMM YYYY'
                    }
                }
            }],
            yAxes: [{
                ticks: {
                    beginAtZero: true,
                    callback: function (value, index, values) {
                        return '$' + value;
                    }
                }
            }]
        },
        legend: {
            display: true,
            position: 'bottom'
        },
        responsive: true
    };

    var ctx = document.getElementById('linegraph').getContext('2d');
    var lineChart = new Chart(ctx, {
        type: 'line',
        data: chartData,
        options: chartOptions
    });
</script>